flags: {}
packages:
- '.'
- location:
    git: git@github.com:mzini/monad-trace
    commit: b75ce1b391cbdd14917feeee95166d55bef5c823
- location:
    git: git@github.com:mzini/gubs
    commit: 9aee6ddfa4b8ba39246178d1c901b6d7f89dc89e
extra-deps:
- ifscs-0.2.0.0
- smtlib2-0.3.1
- union-find-array-0.1.0.2
- multiset-0.2.2
- atto-lisp-0.2.2.2
- data-fix-0.0.3
- failure-0.2.0.3
resolver: lts-5.10
