flags: {}
packages:
- '.'
- location:
    git: git@github.com:mzini/monad-trace
    commit: b75ce1b391cbdd14917feeee95166d55bef5c823
- location:
    git: git@github.com:ComputationWithBoundedResources/gubs
    commit: d9bc7aa55a0e6dc6ca0b4ef1fac8eea7df7f481f
extra-deps:
- smtlib2-1.0
- smtlib2-pipe-1.0
- smtlib2-debug-1.0
- union-find-array-0.1.0.2
- atto-lisp-0.2.2.2
- data-fix-0.0.3
- failure-0.2.0.3
resolver: lts-9.12
