flags: {}
packages:
- '.'
- location:
    git: https://github.com/mzini/monad-trace.git
    commit: 488bd2c09e51cbd16581cdd61fe13059ae62e45e
- location:
    git: https://github.com/ComputationWithBoundedResources/gubs.git
    commit: d9bc7aa55a0e6dc6ca0b4ef1fac8eea7df7f481f
extra-deps:
- smtlib2-1.0
- smtlib2-pipe-1.0
- smtlib2-debug-1.0
- union-find-array-0.1.0.2
- atto-lisp-0.2.2.2
- data-fix-0.0.3
- failure-0.2.0.3
resolver: lts-9.12
